#ifndef __ONNX_H__
#define __ONNX_H__

typedef struct _Onnx__AttributeProto onnx_AttributeProto;
typedef struct _Onnx__ValueInfoProto onnx_ValueInfoProto;
typedef struct _Onnx__NodeProto onnx_NodeProto;
typedef struct _Onnx__ModelProto onnx_ModelProto;
typedef struct _Onnx__StringStringEntryProto onnx_StringStringEntryProto;
typedef struct _Onnx__TensorAnnotation onnx_TensorAnnotation;
typedef struct _Onnx__GraphProto onnx_GraphProto;
typedef struct _Onnx__TensorProto onnx_TensorProto;
typedef struct _Onnx__TensorProto__Segment onnx_TensorProto_Segment;
typedef struct _Onnx__SparseTensorProto onnx_SparseTensorProto;
typedef struct _Onnx__TensorShapeProto onnx_TensorShapeProto;
typedef struct _Onnx__TensorShapeProto__Dimension onnx_TensorShapeProto_Dimension;
typedef struct _Onnx__TypeProto onnx_TypeProto;
typedef struct _Onnx__TypeProto__Tensor onnx_TypeProto_Tensor;
typedef struct _Onnx__TypeProto__Sequence onnx_TypeProto_Sequence;
typedef struct _Onnx__TypeProto__Map onnx_TypeProto_Map;
typedef struct _Onnx__OperatorSetIdProto onnx_OperatorSetIdProto;

#endif /* __ONNX_H__ */
