#ifndef __CONNX_VERSION__
#define __CONNX_VERSION__

#define CONNX_VERSION_MAJOR 0
#define CONNX_VERSION_MINOR 0
#define CONNX_VERSION_MICRO 0
#define CONNX_VERSION_COMMIT "0000000"
#define CONNX_VERSION "0.0.0-0000000"

#endif /* __CONNX_VERSION__ */
