name: Build

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  strategy:
    matrix:
      onnx_version:
        - 1.5.0
        - 1.6.0
        - 1.7.0
        - 1.8.1
        - 1.9.0
        - 1.10.1
        - 1.10.0
        - latest
  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install ubuntu packages to build
      run: |
          sudo apt install cmake ninja-build
          pip3 install numpy
    - name: Create build directory
      run: mkdir build
    - name: build
      working-directory: build
      run: |
          cmake -G Ninja ../ports/linux/ -DCMAKE_BUILD_TYPE=Debug
          ninja
    - name: MNIST
      working-directory: build
      run: |
          ninja mnist
    - name: Clone onnx-connx
      uses: actions/checkout@master
      with:
        repository: tsnlab/onnx-connx
        path: onnx-connx
    - name: ONNX Test Cases
      env:
          ONNX_VERSION: ${{ matrix.onnx_version }}
      run: |
        cd onnx-connx
        cp ../build/connx ./onnx_connx/connx
        [[ "$ONNX_VERSION" = "latest" ]] && ONNX_VERSION='' || ONNX_VERSION="==$ONNX_VERSION"
        pip3 install -U "onnx${ONNX_VERSION}" protobuf tabulate pytest
        pytest -v
