name: Build

on:
  push:
  pull_request:

jobs:
  build_python_package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install ubuntu packages to build
        run: |
            sudo apt install cmake ninja-build
            pip3 install poetry
            poetry config virtualenvs.create false
            poetry install --no-interaction --no-ansi -E numpy
      - name: Build python package
        run: poetry build
      - name: Test pyconnx
        run: python pyconnx/test.py

  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install ubuntu packages to build
        run: |
          sudo apt install cmake ninja-build protobuf-compiler
          pip3 install poetry
          poetry config virtualenvs.create false
          poetry install --no-interaction --no-ansi -E numpy
      - name: Create build directory
        run: mkdir build
      - name: build C files
        working-directory: build
        run: |
            cmake -G Ninja ../ports/linux/ -DCMAKE_BUILD_TYPE=Debug
            ninja
      - name: MNIST
        working-directory: build
        run: |
            ninja mnist

  onnx_tests:
    needs: build_and_test
    strategy:
      fail-fast: false
      matrix:
        onnx_version:
          - 1.5.0
          - 1.6.0
          - 1.7.0
          - 1.8.1
          - 1.9.0
          - 1.10.1
          - 1.11.0
          - latest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Clone onnx-connx
        uses: actions/checkout@master
        with:
          repository: tsnlab/onnx-connx
          path: onnx-connx
      - name: Install ubuntu packages to build
        run: |
          sudo apt install cmake ninja-build protobuf-compiler
      - name: Setup python
        uses: actions/setup-python@v3
        with:
          python-version: 3.8
      - name: Install onnx-connx
        env:
            ONNX_VERSION: ${{ matrix.onnx_version }}
        working-directory: onnx-connx
        run: |
          [[ "$ONNX_VERSION" = "latest" ]] && ONNX_VERSION='' || ONNX_VERSION="~=$ONNX_VERSION"
          pip3 install poetry
          poetry remove connx onnx
          poetry add "onnx$ONNX_VERSION" "../[numpy]"
          poetry install --no-interaction --no-ansi
      - name: Run pytest for onnx test cases
        env:
            ONNX_VERSION: ${{ matrix.onnx_version }}
        working-directory: onnx-connx
        run: poetry run pytest -v

  build_on_rpi:
    strategy:
      fail-fast: false
      matrix:
        host:
          - rpi3
          - rpi4
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Clone to ${{ matrix.host }}
        run: rsync -avz --no-owner --no-group --delete ./ ${{ matrix.host }}:ci/connx/
      - name: Build
        run: |
            ssh ${{ matrix.host }} << EOF
            set -eo pipefail
            cd ci/connx
            cmake -B build -G Ninja -D CMAKE_BUILD_TYPE=Release ports/linux
            cmake --build build
            EOF
