name: Build

on:
    - push
    - pull_request

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install ubuntu packages to lint
      run: sudo apt install clang-format-10
    - name: Check C lint
      run: bin/check-clang-format
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Check python lint
      uses: py-actions/flake8@v2

  build_and_test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Install ubuntu packages to build
      run: |
          sudo apt install cmake ninja-build
          pip3 install numpy
    - name: Create build directory
      run: mkdir build
    - name: build
      working-directory: build
      run: |
          cmake -G Ninja ../ports/linux/ -DCMAKE_BUILD_TYPE=Debug
          ninja
    - name: MNIST
      working-directory: build
      run: |
          ninja mnist
    - name: Clone onnx-connx
      uses: actions/checkout@master
      with:
        repository: semihlab/onnx-connx
        path: onnx-connx
    - name: ONNX Test Cases
      run: |
        cd onnx-connx
        cp ../build/connx ./onnx_connx/connx
        pip3 install -U onnx protobuf tabulate pytest
        pytest
