name: Lint

on:
  push:
    - master
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master
    - name: Run shellcheck
      uses: ludeeus/action-shellcheck@master
    - name: Install ubuntu packages to lint
      run: sudo apt install clang-format-10
    - name: Check C lint
      run: bin/check-clang-format
    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: "3.8"
    - name: Check python lint
      uses: py-actions/flake8@v2
